#--------------------------------------------------------------------------
#
#   Copyright (c) 2002, Tom Hunter (see license.txt)
#
#   Name: Makefile.pterm
#
#   Description:
#       Build X11 version of Desktop Cyber emulation.
#
#--------------------------------------------------------------------------

include Makefile.common

PTOBJS	= $(SOBJS) $(SXOBJS) pterm.o pterm_x11.o ptermcom.o 
pterm:	$(PTOBJS)
	$(CC) $(LDFLAGS) -o $@ $+ $(LIBS) $(XLIBS) $(THRLIBS)

pterm.dep: $(PTOBJS:.o=.d)

include  $(PTOBJS:.o=.d) 

#---------------------------  End Of File  --------------------------------
